import Video from "../models/video.js";

// ===============================
// UPLOAD VIDEO
// ===============================
export const uploadvideo = async (req, res) => {
  try {
    // Check uploaded file
    if (!req.file) {
      return res.status(400).json({
        message: "Please upload a video file.",
      });
    }

    const {
      videotitle,
      videochannel,
      uploader,
      city,
    } = req.body;

    // Check required fields
    if (!videotitle || !videochannel || !uploader) {
      return res.status(400).json({
        message: "Video title, channel and uploader are required.",
      });
    }

    // Allow normal title characters
    const titleRegex = /^[a-zA-Z0-9\s.,!?'"()\-]+$/;

    if (!titleRegex.test(videotitle.trim())) {
      return res.status(400).json({
        message: "Invalid characters in video title.",
      });
    }

    // Create video document
    const file = new Video({
      videotitle: videotitle.trim(),

      videochannel: videochannel.trim(),

      // Actual filename generated by Multer
      filename: req.file.filename,

      // Browser-accessible path
      filepath: `/uploads/${req.file.filename}`,

      // MIME type
      filetype: req.file.mimetype,

      // File size in bytes
      filesize: req.file.size,

      // User who uploaded the video
      uploader: uploader,

      // Regional information
      uploaderCity: city || "Unknown",

      // Initial counters
      views: 0,
      like: 0,
      dislike: 0,
    });

    const savedFile = await file.save();

    return res.status(201).json({
      message: "Video uploaded successfully",
      video: savedFile,
    });
  } catch (error) {
    console.error("Video upload error:", error);

    return res.status(500).json({
      message: "Something went wrong while uploading the video.",
    });
  }
};